import {User, UserEstado} from '../types/user';
import {Orden, OrdenEstado} from '../types/mantenimiento';

const rol = "tecnico"

//---------------------Tecnicos------------------------
export const mockTecnicos: User[] = [
    {
        id: '1',
        iniciales: 'FC',
        name: 'Frank Chacon',
        email:'frankManuel1991@gmail.com',
        rol: rol,
        department: 'frontend',
        status: 'unavailable',

    },
    {
        id: '2',
        iniciales: 'NE',
        name: 'Nour Ehab',
        email: 'NourEhab19@gmail.com',
        rol: rol,
        department: 'cardiology',
        status: 'available',
    },
    {
        id: '3',
        iniciales: 'YD',
        name: 'Yasmin dos Santos',
        email: 'Yasmin2Santos@gmail.com',
        rol: rol,
        department: 'Vet',
        status: 'unavailable',
    },
    {
        id: '4',
        iniciales: 'VC',
        name: 'Valeria Castro',
        email: 'ValeriaCastro@gmail.com',
        rol: rol,
        department: 'pediatrics',
        status: 'available',
    }
];
//---------------------Ordenes de mantenimiento--------------------
export const mockOrdenes: Orden[] = [
  {
    id: 'ORD-001',
    activo: 'Compresor Industrial A-12',
    tecnicoId: '1',
    tecnicoNombre: 'Frank Chacon',
    prioridad: 'alta',
    estado: 'en-proceso',
    tipo: 'correctivo',
    fecha: '2024-05-20',
    fechaCulminacion: '',
  },
  {
    id: 'ORD-002',
    activo: 'Montacargas Yale 2.5T',
    tecnicoId: '2',
    tecnicoNombre: 'Nour Ehab',
    prioridad: 'media',
    estado: 'pendiente',
    tipo: 'preventivo',
    fecha: '2024-05-21',
    fechaCulminacion: '',
  },
  {
    id: 'ORD-003',
    activo: 'Generador Eléctrico 50kVA',
    tecnicoId: '3',
    tecnicoNombre: 'Yasmin dos Santos',
    prioridad: 'alta',
    estado: 'completada',
    tipo: 'correctivo',
    fecha: '2024-05-18',
    fechaCulminacion: '2024-05-19',
  },
  {
    id: 'ORD-004',
    activo: 'Bomba Hidráulica P-500',
    tecnicoId: '4',
    tecnicoNombre: 'Valeria Castro',
    prioridad: 'baja',
    estado: 'pendiente',
    tipo: 'preventivo',
    fecha: '2024-05-22',
    fechaCulminacion: '',
  },
  {
    id: 'ORD-005',
    activo: 'Torre de Enfriamiento C-1',
    tecnicoId: '1',
    tecnicoNombre: 'Frank Chacon',
    prioridad: 'media',
    estado: 'en-proceso',
    tipo: 'correctivo',
    fecha: '2024-05-15',
    fechaCulminacion: '',
  },
  {
    id: 'ORD-006',
    activo: 'Prensa Hidráulica 20T',
    tecnicoId: '2',
    tecnicoNombre: 'Nour Ehab',
    prioridad: 'alta',
    estado: 'completada',
    tipo: 'preventivo',
    fecha: '2024-05-10',
    fechaCulminacion: '2024-05-11',
  },
  {
    id: 'ORD-007',
    activo: 'Aire Acondicionado Central',
    tecnicoId: '4',
    tecnicoNombre: 'Valeria Castro',
    prioridad: 'baja',
    estado: 'completada',
    tipo: 'preventivo',
    fecha: '2024-05-12',
    fechaCulminacion: '2024-05-12',
  },
  {
    id: 'ORD-008',
    activo: 'Cinta Transportadora T-80',
    tecnicoId: '3',
    tecnicoNombre: 'Yasmin dos Santos',
    prioridad: 'media',
    estado: 'pendiente',
    tipo: 'correctivo',
    fecha: '2024-05-23',
    fechaCulminacion: '',
  },
  {
    id: 'ORD-009',
    activo: 'Transformador Eléctrico T2',
    tecnicoId: '1',
    tecnicoNombre: 'Frank Chacon',
    prioridad: 'alta',
    estado: 'en-proceso',
    tipo: 'preventivo',
    fecha: '2024-05-19',
    fechaCulminacion: '',
  },
  {
    id: 'ORD-010',
    activo: 'Elevador de Carga L-5',
    tecnicoId: '2',
    tecnicoNombre: 'Nour Ehab',
    prioridad: 'media',
    estado: 'pendiente',
    tipo: 'correctivo',
    fecha: '2024-05-24',
    fechaCulminacion: '',
  }
];